#!/bin/bash
echo Setting up the environment for Active Harmony server
export HARMONY_ROOT=$PWD
export HARMONY_CONFIG=$HARMONY_ROOT/bin/harmony.cfg
export HARMONY_S_HOST=localhost
export HARMONY_S_PORT=1977
